### ISSUE TITLE
Puppet workflows have been validated in a realistic environment with DAP

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-puppet#207]
Given:

- an existing DAP deployment with at least one secret loaded (in our sample env, Puppet should be set up to point to the L7 LB in GKE)
- a Linux Puppet 6 server
- a Windows Server 201x Puppet 6 agent (on a different machine than the Puppet server, with a different IP)

We will run through the following test flows with our Conjur Puppet module:
- (core team) Set up a host that has an IP restriction to the Puppet agent IP, and provide the host / Conjur config info to the Puppet team
- Attempt to run the Puppet agent and see that the agent receives a 401 response when it attempts to authenticate to DAP
- (core team) Verify that the authentication failure is logged in the audit log, and that it shows the Puppet agent IP (not the Puppet server IP)
- (core team) Add the load balancer IP and the internal k8s IP range as trusted proxies on both Followers
- Attempt to run the agent and see that it's successfully able to retrieve a secret from DAP
- (core team) The IP address is reported correctly in both the server log and the audit log as the Puppet agent IP (not the Puppet server IP)

**Comment by izgeri** [comment]
Notes on the Puppet env if using Puppet Enterprise (cc @hughsaunders):
- AWS has [hosted Puppet Enterprise](https://aws.amazon.com/opsworks/puppetenterprise/)
- [Puppet docs on compile masters](https://puppet.com/docs/puppetserver/5.3/scaling_puppet_server.html)
- [Puppet post on autoscaling compile masters](https://puppet.com/blog/autoscaling-puppet-compile-masters-with-aws/) (may be useful)
- [Puppet docs on installing compilers](https://puppet.com/docs/pe/2019.8/installing_compilers.html)

**Comment by jvanderhoof** [comment]
### Assumptions
- Two Puppet managed nodes:
    1. Windows server, with Puppet agent installed. Will run Puppet Role: `role-1`
    2. Linux server, with Puppet agent installed.  Will run Puppet Role: `role-2`

### Steps
- [ ] Create two Puppet Role manifests and load into Puppet Master  
  - Role 1 should use the Conjur variables `credentials/api-key`, and `credentials/public certificate` (note space in `public certificate`)
  - Role 2 should use the Conjur variables `credentials/authorization-token`, and `credentials/public certificate` (note space in `public certificate`)

- [ ] Load Conjur Policies
  <details>
  <summary>Click to expand</summary>
  
  ```yml
  # puppet-servers.yml
  - !policy
  id: puppet-servers
  body:
    - !layer
    - &hosts
      - !host
        id: role-1
        annotations:
          description: "Windows server"
        restricted_to: <server public IP>

      - !host role-2
        annotations:
          description: "Linux server"
        restricted_to: <server public IP>

    - !grant
      role: !layer
      member: *hosts

  # credentials.yml
  - !policy
  id: credentials
  body:
  - !policy
      id: api-key
      body:
      - !variable

      - !group read
      - !group write

      - !permit
          resource: !variable
          privileges: [ read, execute ]
          role: !group read

      - !permit
          resource: !variable
          privileges: [ update ]
          role: !group write

      - !grant
          member: !group write
          role: !group read
  
  - !policy
      id: "authorization-token"
      body:
      - !variable

      - !group read
      - !group write

      - !permit
          resource: !variable
          privileges: [ read, execute ]
          role: !group read

      - !permit
          resource: !variable
          privileges: [ update ]
          role: !group write

      - !grant
          member: !group write
          role: !group read
    
    - !policy
      id: "public certificate"
      body:
      - !variable

      - !group read
      - !group write

      - !permit
          resource: !variable
          privileges: [ read, execute ]
          role: !group read

      - !permit
          resource: !variable
          privileges: [ update ]
          role: !group write

      - !grant
          member: !group write
          role: !group read

  # role-credential-mapping.yml
  - !grant
    resource: !host puppet-servers/role-1
    role: !group credentials/api-key/read

  - !grant
    resource: !host puppet-servers/role-2
    role: !group credentials/authorization-token/read

  - !grant
    resource: !layer puppet-servers
    role: !group "credentials/public certificate/read"
  ```

  Load the generated API keys into Puppet to insure a role can use the corresponding host API key.
  </details>
- [ ] Set variable values
  <details>
  <summary>Click to expand</summary>
  
  ```sh
  conjur
  ```
  </details>

- [ ] (Puppet) Run Playbook for Role 1 on Windows server. The playbook should use the Conjur host `puppet-servers/role-1` with the corresponding API key.
    **Expected Result**: Puppet run fails because the agent received a 401 response from DAP.
- [ ] (Puppet) Run Playbook for Role 2 on Linux server. The playbook should use the Conjur host `puppet-servers/role-2` with the corresponding API key.
    **Expected Result**: Puppet run fails because the agent received a 401 response from DAP.
- [ ] (DAP) Verify:
  - [ ] Authentication failures are logged in the audit log
  - [ ] Verify audit log shows Follower L7 load balancer IP
- [ ] (DAP) Add the Follower load balancer IP and internal Kubernetes IP range as trusted proxies
  <details>
  <summary>Click to expand</summary>
  
  ```sh
  
  ```
  </details>
- [ ] (Puppet) Update the Playbook, altering the API key so it's no longer correct. Run Playbook for Role 1 on Windows server. The playbook should use the Conjur host `puppet-servers/role-1` with an incorrect API key.
  **Expected Result**: Puppet run fails.

- [ ] (DAP) Verify:
  - [ ] Authentication failure is logged in the audit log
  - [ ] Audit log shows Puppet agent IP (not the Puppet server IP)
